### ISSUE TITLE
node.call_rpc returns false even on success

### ISSUE THREAD

**Issue by davetcoleman** [arpg/Node#15]
Should return true.

Also, is there a better way to detect failure?

**Comment by gsibley** [comment]
Hi Dave,

Can you find the code path for how this happens?  It is not obvious looking
at the code how this is possible.  If you can help us find it I'll fix it
asap.

best,
Gabe

On Fri, Mar 27, 2015 at 11:16 AM, Dave Coleman <notifications@github.com>
wrote:

> Should return true.
>
> Also, is there a better way to detect failure?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/arpg/Node/issues/15>.
>



-- 
Gabe Sibley, PhD

Assistant Professor
Department of Computer Science
University of Colorado, Boulder
--

**Comment by davetcoleman** [comment]
Sorry, I didn't get a chance to look into why it always returned false. I've since worked around this issue so will close it.
